apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: kube-credential
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: frontend
      port:
        number: 80

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: issuance-ingress
  namespace: kube-credential
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/services/issuance/issue
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /issue
        pathType: Prefix
        backend:
          service:
            name: worker
            port:
              number: 5000
              
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: verification-ingress
  namespace: kube-credential
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/services/verification/verify
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /verify
        pathType: Prefix
        backend:
          service:
            name: verification-service
            port:
              number: 5001